// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package loker

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoginRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	User                 *User    `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{1}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LoginResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type RegisterResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{2}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type PekerjaRegisterRequest struct {
	Fullname             string   `protobuf:"bytes,1,opt,name=fullname,proto3" json:"fullname,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Provinsi             string   `protobuf:"bytes,3,opt,name=provinsi,proto3" json:"provinsi,omitempty"`
	KabupatenKota        string   `protobuf:"bytes,4,opt,name=kabupatenKota,proto3" json:"kabupatenKota,omitempty"`
	KodePos              string   `protobuf:"bytes,5,opt,name=kodePos,proto3" json:"kodePos,omitempty"`
	Pekerjaan            string   `protobuf:"bytes,6,opt,name=pekerjaan,proto3" json:"pekerjaan,omitempty"`
	Username             string   `protobuf:"bytes,7,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,8,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PekerjaRegisterRequest) Reset()         { *m = PekerjaRegisterRequest{} }
func (m *PekerjaRegisterRequest) String() string { return proto.CompactTextString(m) }
func (*PekerjaRegisterRequest) ProtoMessage()    {}
func (*PekerjaRegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{3}
}

func (m *PekerjaRegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PekerjaRegisterRequest.Unmarshal(m, b)
}
func (m *PekerjaRegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PekerjaRegisterRequest.Marshal(b, m, deterministic)
}
func (m *PekerjaRegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PekerjaRegisterRequest.Merge(m, src)
}
func (m *PekerjaRegisterRequest) XXX_Size() int {
	return xxx_messageInfo_PekerjaRegisterRequest.Size(m)
}
func (m *PekerjaRegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PekerjaRegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PekerjaRegisterRequest proto.InternalMessageInfo

func (m *PekerjaRegisterRequest) GetFullname() string {
	if m != nil {
		return m.Fullname
	}
	return ""
}

func (m *PekerjaRegisterRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *PekerjaRegisterRequest) GetProvinsi() string {
	if m != nil {
		return m.Provinsi
	}
	return ""
}

func (m *PekerjaRegisterRequest) GetKabupatenKota() string {
	if m != nil {
		return m.KabupatenKota
	}
	return ""
}

func (m *PekerjaRegisterRequest) GetKodePos() string {
	if m != nil {
		return m.KodePos
	}
	return ""
}

func (m *PekerjaRegisterRequest) GetPekerjaan() string {
	if m != nil {
		return m.Pekerjaan
	}
	return ""
}

func (m *PekerjaRegisterRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *PekerjaRegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type PerusahaanRegisterRequest struct {
	Fullname             string   `protobuf:"bytes,1,opt,name=fullname,proto3" json:"fullname,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Provinsi             string   `protobuf:"bytes,3,opt,name=provinsi,proto3" json:"provinsi,omitempty"`
	KabupatenKota        string   `protobuf:"bytes,4,opt,name=kabupatenKota,proto3" json:"kabupatenKota,omitempty"`
	NamaPerusahaan       string   `protobuf:"bytes,5,opt,name=namaPerusahaan,proto3" json:"namaPerusahaan,omitempty"`
	BidangIndustri       string   `protobuf:"bytes,6,opt,name=bidangIndustri,proto3" json:"bidangIndustri,omitempty"`
	AlamatPerusahaan     string   `protobuf:"bytes,7,opt,name=alamatPerusahaan,proto3" json:"alamatPerusahaan,omitempty"`
	Username             string   `protobuf:"bytes,8,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,9,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PerusahaanRegisterRequest) Reset()         { *m = PerusahaanRegisterRequest{} }
func (m *PerusahaanRegisterRequest) String() string { return proto.CompactTextString(m) }
func (*PerusahaanRegisterRequest) ProtoMessage()    {}
func (*PerusahaanRegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{4}
}

func (m *PerusahaanRegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PerusahaanRegisterRequest.Unmarshal(m, b)
}
func (m *PerusahaanRegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PerusahaanRegisterRequest.Marshal(b, m, deterministic)
}
func (m *PerusahaanRegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PerusahaanRegisterRequest.Merge(m, src)
}
func (m *PerusahaanRegisterRequest) XXX_Size() int {
	return xxx_messageInfo_PerusahaanRegisterRequest.Size(m)
}
func (m *PerusahaanRegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PerusahaanRegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PerusahaanRegisterRequest proto.InternalMessageInfo

func (m *PerusahaanRegisterRequest) GetFullname() string {
	if m != nil {
		return m.Fullname
	}
	return ""
}

func (m *PerusahaanRegisterRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *PerusahaanRegisterRequest) GetProvinsi() string {
	if m != nil {
		return m.Provinsi
	}
	return ""
}

func (m *PerusahaanRegisterRequest) GetKabupatenKota() string {
	if m != nil {
		return m.KabupatenKota
	}
	return ""
}

func (m *PerusahaanRegisterRequest) GetNamaPerusahaan() string {
	if m != nil {
		return m.NamaPerusahaan
	}
	return ""
}

func (m *PerusahaanRegisterRequest) GetBidangIndustri() string {
	if m != nil {
		return m.BidangIndustri
	}
	return ""
}

func (m *PerusahaanRegisterRequest) GetAlamatPerusahaan() string {
	if m != nil {
		return m.AlamatPerusahaan
	}
	return ""
}

func (m *PerusahaanRegisterRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *PerusahaanRegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func init() {
	proto.RegisterType((*LoginRequest)(nil), "loker.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "loker.LoginResponse")
	proto.RegisterType((*RegisterResponse)(nil), "loker.RegisterResponse")
	proto.RegisterType((*PekerjaRegisterRequest)(nil), "loker.PekerjaRegisterRequest")
	proto.RegisterType((*PerusahaanRegisterRequest)(nil), "loker.PerusahaanRegisterRequest")
}

func init() { proto.RegisterFile("auth.proto", fileDescriptor_8bbd6f3875b0e874) }

var fileDescriptor_8bbd6f3875b0e874 = []byte{
	// 418 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x53, 0xcd, 0x8e, 0x94, 0x40,
	0x18, 0x5c, 0xc6, 0x61, 0x97, 0xf9, 0xd6, 0xd5, 0x4d, 0xbb, 0x51, 0x24, 0x1a, 0x37, 0xc4, 0x18,
	0x63, 0xcc, 0x1c, 0x56, 0x1f, 0x40, 0x2f, 0x26, 0x66, 0x3c, 0x8c, 0x24, 0x3e, 0xc0, 0x37, 0xe1,
	0x93, 0x41, 0xa0, 0x1b, 0xfb, 0x47, 0x1f, 0xd0, 0xd7, 0xf0, 0x51, 0x3c, 0x18, 0xba, 0x1b, 0x18,
	0x50, 0xe7, 0xec, 0xb1, 0xea, 0xeb, 0xae, 0xfe, 0xaa, 0x28, 0x00, 0xd0, 0xe8, 0xfd, 0xba, 0x95,
	0x42, 0x0b, 0x16, 0xd6, 0xa2, 0x22, 0x99, 0x80, 0x51, 0x24, 0x1d, 0x95, 0xbe, 0x81, 0xdb, 0x1f,
	0x44, 0x51, 0xf2, 0x8c, 0xbe, 0x1a, 0x52, 0x9a, 0x5d, 0x41, 0x48, 0x0d, 0x96, 0x75, 0x1c, 0x5c,
	0x07, 0xcf, 0x57, 0x99, 0x03, 0x2c, 0x81, 0xa8, 0x45, 0xa5, 0xbe, 0x0b, 0x99, 0xc7, 0x0b, 0x3b,
	0x18, 0x70, 0xfa, 0x0e, 0x2e, 0xbc, 0x82, 0x6a, 0x05, 0x57, 0xd4, 0x49, 0x68, 0x51, 0x11, 0xef,
	0x25, 0x2c, 0x60, 0x4f, 0x60, 0xd9, 0x3d, 0x6b, 0xaf, 0x9f, 0xdf, 0x9c, 0xaf, 0xed, 0x2a, 0xeb,
	0x4f, 0x8a, 0x64, 0x66, 0x07, 0xe9, 0x4b, 0xb8, 0xcc, 0xa8, 0x28, 0x95, 0x26, 0x39, 0x48, 0xc5,
	0x70, 0xd6, 0x90, 0x52, 0x58, 0x90, 0x17, 0xeb, 0x61, 0xfa, 0x2b, 0x80, 0xfb, 0x5b, 0xaa, 0x48,
	0x7e, 0xc1, 0xf1, 0x96, 0xb3, 0x90, 0x40, 0xf4, 0xd9, 0xd4, 0x35, 0xc7, 0xa6, 0xbf, 0x35, 0xe0,
	0xd1, 0xde, 0x62, 0x6e, 0x4f, 0x8a, 0x6f, 0x25, 0x57, 0x65, 0x7c, 0xcb, 0xdb, 0xf3, 0x98, 0x3d,
	0x85, 0x8b, 0x0a, 0x77, 0xa6, 0x45, 0x4d, 0x7c, 0x23, 0x34, 0xc6, 0x4b, 0x7b, 0x60, 0x4a, 0x76,
	0x8b, 0x56, 0x22, 0xa7, 0xad, 0x50, 0x71, 0xe8, 0x16, 0xf5, 0x90, 0x3d, 0x82, 0x55, 0xeb, 0xf6,
	0x44, 0x1e, 0x9f, 0xda, 0xd9, 0x48, 0x74, 0x2f, 0x77, 0xe6, 0xed, 0xae, 0x67, 0xee, 0xe5, 0x1e,
	0x4f, 0x42, 0x8f, 0x66, 0xa1, 0xff, 0x58, 0xc0, 0xc3, 0x2d, 0x49, 0xa3, 0x70, 0x8f, 0xc8, 0xff,
	0x87, 0x04, 0x9e, 0xc1, 0x1d, 0x8e, 0x0d, 0x8e, 0x4b, 0xf9, 0x20, 0x66, 0x6c, 0x77, 0x6e, 0x57,
	0xe6, 0xc8, 0x8b, 0xf7, 0x3c, 0x37, 0x4a, 0xcb, 0xd2, 0x87, 0x32, 0x63, 0xd9, 0x0b, 0xb8, 0xc4,
	0x1a, 0x1b, 0xd4, 0x07, 0x8a, 0x2e, 0xa1, 0x3f, 0xf8, 0x49, 0x8a, 0xd1, 0x91, 0x14, 0x57, 0xd3,
	0x14, 0x6f, 0x7e, 0x06, 0xb0, 0x7c, 0x6b, 0xf4, 0x9e, 0xbd, 0x86, 0xd0, 0x76, 0x98, 0xdd, 0xf3,
	0xbd, 0x3c, 0xfc, 0x27, 0x92, 0xab, 0x29, 0xe9, 0xba, 0x99, 0x9e, 0xb0, 0x0d, 0xdc, 0xed, 0x93,
	0xf7, 0x55, 0x64, 0x8f, 0xfd, 0xd1, 0xbf, 0x57, 0x33, 0x79, 0xe0, 0xc7, 0xf3, 0xa2, 0xa7, 0x27,
	0xec, 0x23, 0xb0, 0x51, 0x6c, 0x70, 0x76, 0x3d, 0xe8, 0xfd, 0xe3, 0x5b, 0x1f, 0x91, 0xdc, 0x9d,
	0xda, 0x5f, 0xfc, 0xd5, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7b, 0xdd, 0xc7, 0x9c, 0x03, 0x04,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthClient is the client API for Auth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	RegisterPekerja(ctx context.Context, in *PekerjaRegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	RegisterPerusahaan(ctx context.Context, in *PerusahaanRegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
}

type authClient struct {
	cc *grpc.ClientConn
}

func NewAuthClient(cc *grpc.ClientConn) AuthClient {
	return &authClient{cc}
}

func (c *authClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/loker.Auth/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) RegisterPekerja(ctx context.Context, in *PekerjaRegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, "/loker.Auth/RegisterPekerja", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) RegisterPerusahaan(ctx context.Context, in *PerusahaanRegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, "/loker.Auth/RegisterPerusahaan", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServer is the server API for Auth service.
type AuthServer interface {
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	RegisterPekerja(context.Context, *PekerjaRegisterRequest) (*RegisterResponse, error)
	RegisterPerusahaan(context.Context, *PerusahaanRegisterRequest) (*RegisterResponse, error)
}

// UnimplementedAuthServer can be embedded to have forward compatible implementations.
type UnimplementedAuthServer struct {
}

func (*UnimplementedAuthServer) Login(ctx context.Context, req *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedAuthServer) RegisterPekerja(ctx context.Context, req *PekerjaRegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterPekerja not implemented")
}
func (*UnimplementedAuthServer) RegisterPerusahaan(ctx context.Context, req *PerusahaanRegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterPerusahaan not implemented")
}

func RegisterAuthServer(s *grpc.Server, srv AuthServer) {
	s.RegisterService(&_Auth_serviceDesc, srv)
}

func _Auth_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/loker.Auth/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_RegisterPekerja_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PekerjaRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).RegisterPekerja(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/loker.Auth/RegisterPekerja",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).RegisterPekerja(ctx, req.(*PekerjaRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_RegisterPerusahaan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PerusahaanRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).RegisterPerusahaan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/loker.Auth/RegisterPerusahaan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).RegisterPerusahaan(ctx, req.(*PerusahaanRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Auth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "loker.Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _Auth_Login_Handler,
		},
		{
			MethodName: "RegisterPekerja",
			Handler:    _Auth_RegisterPekerja_Handler,
		},
		{
			MethodName: "RegisterPerusahaan",
			Handler:    _Auth_RegisterPerusahaan_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}
