// Code generated by protoc-gen-go. DO NOT EDIT.
// source: code_message.proto

package loker

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CodeMessage int32

const (
	CodeMessage_CodeMessage_UNKNOWN CodeMessage = 0
	CodeMessage_UserCreated         CodeMessage = 1
)

var CodeMessage_name = map[int32]string{
	0: "CodeMessage_UNKNOWN",
	1: "UserCreated",
}

var CodeMessage_value = map[string]int32{
	"CodeMessage_UNKNOWN": 0,
	"UserCreated":         1,
}

func (x CodeMessage) String() string {
	return proto.EnumName(CodeMessage_name, int32(x))
}

func (CodeMessage) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bc1dad5cd4007da2, []int{0}
}

func init() {
	proto.RegisterEnum("loker.CodeMessage", CodeMessage_name, CodeMessage_value)
}

func init() { proto.RegisterFile("code_message.proto", fileDescriptor_bc1dad5cd4007da2) }

var fileDescriptor_bc1dad5cd4007da2 = []byte{
	// 100 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4a, 0xce, 0x4f, 0x49,
	0x8d, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62,
	0xcd, 0xc9, 0xcf, 0x4e, 0x2d, 0xd2, 0x32, 0xe7, 0xe2, 0x76, 0xce, 0x4f, 0x49, 0xf5, 0x85, 0xc8,
	0x09, 0x89, 0x73, 0x09, 0x23, 0x71, 0xe3, 0x43, 0xfd, 0xbc, 0xfd, 0xfc, 0xc3, 0xfd, 0x04, 0x18,
	0x84, 0xf8, 0xb9, 0xb8, 0x43, 0x8b, 0x53, 0x8b, 0x9c, 0x8b, 0x52, 0x13, 0x4b, 0x52, 0x53, 0x04,
	0x18, 0x93, 0xd8, 0xc0, 0xc6, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x71, 0x76, 0xf4, 0xf8,
	0x5c, 0x00, 0x00, 0x00,
}
