// Code generated by protoc-gen-go. DO NOT EDIT.
// source: member.proto

package loker

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Member struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	IdUser               int32    `protobuf:"varint,2,opt,name=id_user,json=idUser,proto3" json:"id_user,omitempty"`
	IdPekerjaan          int32    `protobuf:"varint,3,opt,name=id_pekerjaan,json=idPekerjaan,proto3" json:"id_pekerjaan,omitempty"`
	CoverProfile         string   `protobuf:"bytes,4,opt,name=cover_profile,json=coverProfile,proto3" json:"cover_profile,omitempty"`
	NamaLengkap          string   `protobuf:"bytes,5,opt,name=nama_lengkap,json=namaLengkap,proto3" json:"nama_lengkap,omitempty"`
	NoKtp                string   `protobuf:"bytes,6,opt,name=no_ktp,json=noKtp,proto3" json:"no_ktp,omitempty"`
	DeskripsiMember      string   `protobuf:"bytes,7,opt,name=deskripsi_member,json=deskripsiMember,proto3" json:"deskripsi_member,omitempty"`
	KotaMember           string   `protobuf:"bytes,8,opt,name=kota_member,json=kotaMember,proto3" json:"kota_member,omitempty"`
	ProvinsiMember       string   `protobuf:"bytes,9,opt,name=provinsi_member,json=provinsiMember,proto3" json:"provinsi_member,omitempty"`
	NoHpMember           string   `protobuf:"bytes,10,opt,name=no_hp_member,json=noHpMember,proto3" json:"no_hp_member,omitempty"`
	NoWa                 string   `protobuf:"bytes,11,opt,name=no_wa,json=noWa,proto3" json:"no_wa,omitempty"`
	EmailMember          string   `protobuf:"bytes,12,opt,name=email_member,json=emailMember,proto3" json:"email_member,omitempty"`
	Alamat               string   `protobuf:"bytes,13,opt,name=alamat,proto3" json:"alamat,omitempty"`
	ScanKtp              string   `protobuf:"bytes,14,opt,name=scan_ktp,json=scanKtp,proto3" json:"scan_ktp,omitempty"`
	Skills               string   `protobuf:"bytes,15,opt,name=skills,proto3" json:"skills,omitempty"`
	WebPersonal          string   `protobuf:"bytes,16,opt,name=web_personal,json=webPersonal,proto3" json:"web_personal,omitempty"`
	Usia                 int32    `protobuf:"varint,17,opt,name=usia,proto3" json:"usia,omitempty"`
	SudahBekerja         bool     `protobuf:"varint,18,opt,name=sudahBekerja,proto3" json:"sudahBekerja,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Member) Reset()         { *m = Member{} }
func (m *Member) String() string { return proto.CompactTextString(m) }
func (*Member) ProtoMessage()    {}
func (*Member) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b9836b7e13de206, []int{0}
}

func (m *Member) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Member.Unmarshal(m, b)
}
func (m *Member) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Member.Marshal(b, m, deterministic)
}
func (m *Member) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Member.Merge(m, src)
}
func (m *Member) XXX_Size() int {
	return xxx_messageInfo_Member.Size(m)
}
func (m *Member) XXX_DiscardUnknown() {
	xxx_messageInfo_Member.DiscardUnknown(m)
}

var xxx_messageInfo_Member proto.InternalMessageInfo

func (m *Member) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Member) GetIdUser() int32 {
	if m != nil {
		return m.IdUser
	}
	return 0
}

func (m *Member) GetIdPekerjaan() int32 {
	if m != nil {
		return m.IdPekerjaan
	}
	return 0
}

func (m *Member) GetCoverProfile() string {
	if m != nil {
		return m.CoverProfile
	}
	return ""
}

func (m *Member) GetNamaLengkap() string {
	if m != nil {
		return m.NamaLengkap
	}
	return ""
}

func (m *Member) GetNoKtp() string {
	if m != nil {
		return m.NoKtp
	}
	return ""
}

func (m *Member) GetDeskripsiMember() string {
	if m != nil {
		return m.DeskripsiMember
	}
	return ""
}

func (m *Member) GetKotaMember() string {
	if m != nil {
		return m.KotaMember
	}
	return ""
}

func (m *Member) GetProvinsiMember() string {
	if m != nil {
		return m.ProvinsiMember
	}
	return ""
}

func (m *Member) GetNoHpMember() string {
	if m != nil {
		return m.NoHpMember
	}
	return ""
}

func (m *Member) GetNoWa() string {
	if m != nil {
		return m.NoWa
	}
	return ""
}

func (m *Member) GetEmailMember() string {
	if m != nil {
		return m.EmailMember
	}
	return ""
}

func (m *Member) GetAlamat() string {
	if m != nil {
		return m.Alamat
	}
	return ""
}

func (m *Member) GetScanKtp() string {
	if m != nil {
		return m.ScanKtp
	}
	return ""
}

func (m *Member) GetSkills() string {
	if m != nil {
		return m.Skills
	}
	return ""
}

func (m *Member) GetWebPersonal() string {
	if m != nil {
		return m.WebPersonal
	}
	return ""
}

func (m *Member) GetUsia() int32 {
	if m != nil {
		return m.Usia
	}
	return 0
}

func (m *Member) GetSudahBekerja() bool {
	if m != nil {
		return m.SudahBekerja
	}
	return false
}

func init() {
	proto.RegisterType((*Member)(nil), "loker.Member")
}

func init() { proto.RegisterFile("member.proto", fileDescriptor_9b9836b7e13de206) }

var fileDescriptor_9b9836b7e13de206 = []byte{
	// 367 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x92, 0x41, 0xae, 0xd3, 0x30,
	0x10, 0x86, 0x95, 0x92, 0xa4, 0x7d, 0x93, 0xbc, 0xb6, 0x18, 0x51, 0xcc, 0x8a, 0x50, 0x16, 0x94,
	0x0d, 0x1b, 0x6e, 0xc0, 0x0a, 0x09, 0x90, 0xaa, 0x4a, 0x88, 0xa5, 0x35, 0xa9, 0x0d, 0x35, 0x71,
	0x6c, 0xcb, 0x4e, 0xdb, 0x2b, 0x71, 0x4c, 0x94, 0x71, 0x02, 0x62, 0x97, 0xf9, 0xe6, 0x9b, 0xb1,
	0xfe, 0xd8, 0x50, 0xf7, 0xaa, 0x6f, 0x55, 0x78, 0xef, 0x83, 0x1b, 0x1c, 0x2b, 0x8c, 0xeb, 0x54,
	0xd8, 0xff, 0xce, 0xa1, 0xfc, 0x4a, 0x9c, 0xad, 0x61, 0xa1, 0x25, 0xcf, 0x9a, 0xec, 0x50, 0x9c,
	0x16, 0x5a, 0xb2, 0x17, 0xb0, 0xd4, 0x52, 0x5c, 0xa3, 0x0a, 0x7c, 0x41, 0xb0, 0xd4, 0xf2, 0x5b,
	0x54, 0x81, 0xbd, 0x86, 0x5a, 0x4b, 0xe1, 0x55, 0xa7, 0xc2, 0x2f, 0x44, 0xcb, 0x9f, 0x50, 0xb7,
	0xd2, 0xf2, 0x38, 0x23, 0xf6, 0x06, 0x1e, 0xcf, 0xee, 0xa6, 0x82, 0xf0, 0xc1, 0xfd, 0xd0, 0x46,
	0xf1, 0xbc, 0xc9, 0x0e, 0x0f, 0xa7, 0x9a, 0xe0, 0x31, 0xb1, 0x71, 0x8f, 0xc5, 0x1e, 0x85, 0x51,
	0xf6, 0x67, 0x87, 0x9e, 0x17, 0xe4, 0x54, 0x23, 0xfb, 0x92, 0x10, 0x7b, 0x0e, 0xa5, 0x75, 0xa2,
	0x1b, 0x3c, 0x2f, 0xa9, 0x59, 0x58, 0xf7, 0x79, 0xf0, 0xec, 0x1d, 0x6c, 0xa5, 0x8a, 0x5d, 0xd0,
	0x3e, 0x6a, 0x91, 0x62, 0xf1, 0x25, 0x09, 0x9b, 0xbf, 0x7c, 0x4a, 0xf5, 0x0a, 0xaa, 0xce, 0x0d,
	0x38, 0x5b, 0x2b, 0xb2, 0x60, 0x44, 0x93, 0xf0, 0x16, 0x36, 0x3e, 0xb8, 0x9b, 0xb6, 0xff, 0x56,
	0x3d, 0x90, 0xb4, 0x9e, 0xf1, 0x24, 0x36, 0x50, 0x5b, 0x27, 0x2e, 0x7e, 0xb6, 0x20, 0xad, 0xb2,
	0xee, 0x93, 0x9f, 0x8c, 0x67, 0x50, 0x58, 0x27, 0xee, 0xc8, 0x2b, 0x6a, 0xe5, 0xd6, 0x7d, 0xc7,
	0x31, 0xa5, 0xea, 0x51, 0x9b, 0x79, 0xac, 0x4e, 0x29, 0x89, 0x4d, 0x73, 0x3b, 0x28, 0xd1, 0x60,
	0x8f, 0x03, 0x7f, 0xa4, 0xe6, 0x54, 0xb1, 0x97, 0xb0, 0x8a, 0x67, 0xb4, 0x94, 0x7f, 0x4d, 0x9d,
	0xe5, 0x58, 0x8f, 0x7f, 0x60, 0x07, 0x65, 0xec, 0xb4, 0x31, 0x91, 0x6f, 0xd2, 0x48, 0xaa, 0xc6,
	0xd3, 0xee, 0xaa, 0x15, 0x5e, 0x85, 0xe8, 0x2c, 0x1a, 0xbe, 0x4d, 0xa7, 0xdd, 0x55, 0x7b, 0x9c,
	0x10, 0x63, 0x90, 0x5f, 0xa3, 0x46, 0xfe, 0x94, 0xae, 0x8d, 0xbe, 0xd9, 0x1e, 0xea, 0x78, 0x95,
	0x78, 0xf9, 0x98, 0x6e, 0x90, 0xb3, 0x26, 0x3b, 0xac, 0x4e, 0xff, 0xb1, 0xb6, 0xa4, 0x87, 0xf3,
	0xe1, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1d, 0x7f, 0x18, 0x47, 0x48, 0x02, 0x00, 0x00,
}
