// Code generated by protoc-gen-go. DO NOT EDIT.
// source: resp_message.proto

package loker

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Code int32

const (
	Code_Code_UNKNOWN Code = 0
	Code_UserCreated  Code = 1
)

var Code_name = map[int32]string{
	0: "Code_UNKNOWN",
	1: "UserCreated",
}

var Code_value = map[string]int32{
	"Code_UNKNOWN": 0,
	"UserCreated":  1,
}

func (x Code) String() string {
	return proto.EnumName(Code_name, int32(x))
}

func (Code) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cb6e8ea233af33b4, []int{0}
}

type RespMessage struct {
	Code                 Code     `protobuf:"varint,1,opt,name=code,proto3,enum=loker.Code" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespMessage) Reset()         { *m = RespMessage{} }
func (m *RespMessage) String() string { return proto.CompactTextString(m) }
func (*RespMessage) ProtoMessage()    {}
func (*RespMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb6e8ea233af33b4, []int{0}
}

func (m *RespMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespMessage.Unmarshal(m, b)
}
func (m *RespMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespMessage.Marshal(b, m, deterministic)
}
func (m *RespMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespMessage.Merge(m, src)
}
func (m *RespMessage) XXX_Size() int {
	return xxx_messageInfo_RespMessage.Size(m)
}
func (m *RespMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_RespMessage.DiscardUnknown(m)
}

var xxx_messageInfo_RespMessage proto.InternalMessageInfo

func (m *RespMessage) GetCode() Code {
	if m != nil {
		return m.Code
	}
	return Code_Code_UNKNOWN
}

func (m *RespMessage) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterEnum("loker.Code", Code_name, Code_value)
	proto.RegisterType((*RespMessage)(nil), "loker.RespMessage")
}

func init() { proto.RegisterFile("resp_message.proto", fileDescriptor_cb6e8ea233af33b4) }

var fileDescriptor_cb6e8ea233af33b4 = []byte{
	// 148 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2a, 0x4a, 0x2d, 0x2e,
	0x88, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62,
	0xcd, 0xc9, 0xcf, 0x4e, 0x2d, 0x52, 0xf2, 0xe0, 0xe2, 0x0e, 0x4a, 0x2d, 0x2e, 0xf0, 0x85, 0xc8,
	0x09, 0xc9, 0x73, 0xb1, 0x24, 0xe7, 0xa7, 0xa4, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0xf0, 0x19, 0x71,
	0xeb, 0x81, 0x15, 0xe9, 0x39, 0xe7, 0xa7, 0xa4, 0x06, 0x81, 0x25, 0x84, 0x24, 0xb8, 0xd8, 0xa1,
	0xe6, 0x48, 0x30, 0x29, 0x30, 0x6a, 0x70, 0x06, 0xc1, 0xb8, 0x5a, 0x9a, 0x5c, 0x2c, 0x20, 0x75,
	0x42, 0x02, 0x5c, 0x3c, 0x20, 0x3a, 0x3e, 0xd4, 0xcf, 0xdb, 0xcf, 0x3f, 0xdc, 0x4f, 0x80, 0x41,
	0x88, 0x9f, 0x8b, 0x3b, 0xb4, 0x38, 0xb5, 0xc8, 0xb9, 0x28, 0x35, 0xb1, 0x24, 0x35, 0x45, 0x80,
	0x31, 0x89, 0x0d, 0xec, 0x04, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x74, 0x6b, 0x5b, 0x6e,
	0x98, 0x00, 0x00, 0x00,
}
