// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package loker

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Level int32

const (
	Level_Level_UNKNOWN Level = 0
	Level_ADMIN         Level = 1
	Level_MEMBER        Level = 2
	Level_PERUSAHAAN    Level = 3
)

var Level_name = map[int32]string{
	0: "Level_UNKNOWN",
	1: "ADMIN",
	2: "MEMBER",
	3: "PERUSAHAAN",
}

var Level_value = map[string]int32{
	"Level_UNKNOWN": 0,
	"ADMIN":         1,
	"MEMBER":        2,
	"PERUSAHAAN":    3,
}

func (x Level) String() string {
	return proto.EnumName(Level_name, int32(x))
}

func (Level) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

type User struct {
	Id                   int32                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username             string               `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Foto                 string               `protobuf:"bytes,3,opt,name=foto,proto3" json:"foto,omitempty"`
	TglDibuat            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=tgl_dibuat,json=tglDibuat,proto3" json:"tgl_dibuat,omitempty"`
	Level                Level                `protobuf:"varint,5,opt,name=level,proto3,enum=loker.Level" json:"level,omitempty"`
	Verifikasi           bool                 `protobuf:"varint,6,opt,name=verifikasi,proto3" json:"verifikasi,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetFoto() string {
	if m != nil {
		return m.Foto
	}
	return ""
}

func (m *User) GetTglDibuat() *timestamp.Timestamp {
	if m != nil {
		return m.TglDibuat
	}
	return nil
}

func (m *User) GetLevel() Level {
	if m != nil {
		return m.Level
	}
	return Level_Level_UNKNOWN
}

func (m *User) GetVerifikasi() bool {
	if m != nil {
		return m.Verifikasi
	}
	return false
}

type UserRequestId struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRequestId) Reset()         { *m = UserRequestId{} }
func (m *UserRequestId) String() string { return proto.CompactTextString(m) }
func (*UserRequestId) ProtoMessage()    {}
func (*UserRequestId) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *UserRequestId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRequestId.Unmarshal(m, b)
}
func (m *UserRequestId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRequestId.Marshal(b, m, deterministic)
}
func (m *UserRequestId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRequestId.Merge(m, src)
}
func (m *UserRequestId) XXX_Size() int {
	return xxx_messageInfo_UserRequestId.Size(m)
}
func (m *UserRequestId) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRequestId.DiscardUnknown(m)
}

var xxx_messageInfo_UserRequestId proto.InternalMessageInfo

func (m *UserRequestId) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterEnum("loker.Level", Level_name, Level_value)
	proto.RegisterType((*User)(nil), "loker.User")
	proto.RegisterType((*UserRequestId)(nil), "loker.UserRequestId")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 286 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0x41, 0x4f, 0xc2, 0x30,
	0x14, 0xc7, 0xed, 0xa0, 0x84, 0x3d, 0x85, 0xcc, 0x77, 0x6a, 0x38, 0xc8, 0xc2, 0x69, 0xf1, 0x50,
	0x12, 0x3c, 0x79, 0x9c, 0x81, 0x44, 0xa2, 0x4c, 0x53, 0x25, 0x1e, 0xc9, 0xc8, 0xba, 0xa5, 0xa1,
	0xb3, 0xb8, 0x75, 0x7c, 0x43, 0xbf, 0x97, 0x59, 0x17, 0x0c, 0xb7, 0xd7, 0x5f, 0x5f, 0xfe, 0xff,
	0xf7, 0x03, 0x68, 0x6a, 0x59, 0xf1, 0x63, 0x65, 0xac, 0x41, 0xaa, 0xcd, 0x41, 0x56, 0x93, 0x69,
	0x61, 0x4c, 0xa1, 0xe5, 0xdc, 0xc1, 0x7d, 0x93, 0xcf, 0xad, 0x2a, 0x65, 0x6d, 0xd3, 0xf2, 0xd8,
	0xed, 0xcd, 0x7e, 0x09, 0xf4, 0xb7, 0xb5, 0xac, 0x70, 0x0c, 0x9e, 0xca, 0x18, 0x09, 0x49, 0x44,
	0x85, 0xa7, 0x32, 0x9c, 0xc0, 0xb0, 0x8d, 0xfb, 0x4e, 0x4b, 0xc9, 0xbc, 0x90, 0x44, 0xbe, 0xf8,
	0x7f, 0x23, 0x42, 0x3f, 0x37, 0xd6, 0xb0, 0x9e, 0xe3, 0x6e, 0xc6, 0x47, 0x00, 0x5b, 0xe8, 0x5d,
	0xa6, 0xf6, 0x4d, 0x6a, 0x59, 0x3f, 0x24, 0xd1, 0xf5, 0x62, 0xc2, 0xbb, 0x7a, 0x7e, 0xae, 0xe7,
	0x9f, 0xe7, 0x7a, 0xe1, 0xdb, 0x42, 0x2f, 0xdd, 0x32, 0xce, 0x80, 0x6a, 0x79, 0x92, 0x9a, 0xd1,
	0x90, 0x44, 0xe3, 0xc5, 0x0d, 0x77, 0xb7, 0xf3, 0xd7, 0x96, 0x89, 0xee, 0x0b, 0xef, 0x00, 0x4e,
	0xb2, 0x52, 0xb9, 0x3a, 0xa4, 0xb5, 0x62, 0x83, 0x90, 0x44, 0x43, 0x71, 0x41, 0x66, 0x53, 0x18,
	0xb5, 0x1a, 0x42, 0xfe, 0x34, 0xb2, 0xb6, 0xeb, 0xec, 0xc2, 0xc7, 0x6f, 0x7d, 0xee, 0x63, 0xa0,
	0x2e, 0x10, 0x6f, 0x61, 0xe4, 0x86, 0xdd, 0x36, 0x79, 0x49, 0xde, 0xbe, 0x92, 0xe0, 0x0a, 0x7d,
	0xa0, 0xf1, 0x72, 0xb3, 0x4e, 0x02, 0x82, 0x00, 0x83, 0xcd, 0x6a, 0xf3, 0xb4, 0x12, 0x81, 0x87,
	0x63, 0x80, 0xf7, 0x95, 0xd8, 0x7e, 0xc4, 0xcf, 0x71, 0x9c, 0x04, 0xbd, 0xfd, 0xc0, 0x69, 0x3c,
	0xfc, 0x05, 0x00, 0x00, 0xff, 0xff, 0xc7, 0x92, 0xc5, 0x67, 0x68, 0x01, 0x00, 0x00,
}
